# This is a basic workflow to help you get started with Actions

name: test-lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clonning_repository_and_install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: cloning repository
        uses: actions/checkout@master
      - name: name_folder
        run: ls -la
      - name: installing python
        uses: actions/setup-python@v1
      - name: install poetry 
        uses: dschep/install-poetry-action@v1.3
      - name: run poetry and make file
        run: poetry run brain-games
        
        
        
        
        

        
        

       
