# This is a basic workflow to help you get started with Actions

name: test-lint

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clonning_repository:
    runs-on: ubuntu-latest
    steps:
      - name: cloning repository
        uses: actions/checkout@v1
      - name: name_folder
        run: ls -la
  Installing_and_running_linter:
    runs-on: ubuntu-latest
    needs: [clonning_repository]
    
    steps:
      - name: installing_flake8, poetry and start make
        run: | 
         python -m pip install flake8
         curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
         make lint

         
           
        
        
        
        
        

        
        

       
